name: Python application

on:
  push:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Extract and mask client_id and client_secret
      run: |
        client_id=$(grep 'client_id' src/hello_world.py | cut -d '"' -f 2)
        client_secret=$(grep 'client_secret' src/hello_world.py | cut -d '"' -f 2)
        echo "::add-mask::$client_id"
        echo "::add-mask::$client_secret"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip

    - name: Run hello_world.py
      run: |
        python src/hello_world.py
